AWSTemplateFormatVersion: '2010-09-09'

Description: This AWS CloudFormation Template that configures the Container DevSecOps Demo Environment.

Parameters:

  EnvironmentName:
    Type: String
    Default: container-security-demo
    Description: Prefix for resources

  DevSecOpsResourcesBucket:
    Type: String
    Default: eksdevsecopsdemo
    Description: Bucket to store required build resources

  AZ1:
    Description: The AZ for Public1 and Private1 Subnets for EKS VPC
    Type: 'AWS::EC2::AvailabilityZone::Name'
  AZ2:
    Description: The AZ for Public2 and Private2 Subnets for EKS VPC
    Type: 'AWS::EC2::AvailabilityZone::Name'
  AZ3:
    Description: The AZ for Public3 and Private3 Subnets for EKS VPC
    Type: 'AWS::EC2::AvailabilityZone::Name'

  FailWhen:
    Type: String
    Default: High
    AllowedValues:
      - Low
      - Medium
      - High
      - Critical
    Description: Threshold to fail the pipeline if app image has vulnerabilities


Resources:

  AnchoreVpcStack:
    Type: AWS::CloudFormation::Stack	
    Properties:
      Parameters:
        EnvironmentName: !Ref EnvironmentName

      TemplateURL: https://s3.amazonaws.com/eksdevsecopsdemo/anchore-vpc.yml

  AnchoreStack:
    DependsOn: AnchoreVpcStack
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
         ResourceName: !Ref EnvironmentName
         DevSecOpsResources: !Ref DevSecOpsResourcesBucket

      TemplateURL: https://s3.amazonaws.com/eksdevsecopsdemo/anchore-fargate.yml
 
  EKSVPCStack:
    DependsOn: AnchoreStack
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        AZ1: !Ref AZ1
        AZ2: !Ref AZ2
        AZ3: !Ref AZ3
        BucketName: !Ref DevSecOpsResourcesBucket

      TemplateURL: https://s3.amazonaws.com/eksdevsecopsdemo/eks-vpc.yml
      
  EKSMNGStack:
    DependsOn: EKSVPCStack
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        BucketName: !Ref DevSecOpsResourcesBucket
        EnvironmentName: !Ref EnvironmentName
        ClusterName: !GetAtt EKSVPCStack.Outputs.EKSClusterName
        PrivateSubnet1: !GetAtt EKSVPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt EKSVPCStack.Outputs.PrivateSubnet2
        PrivateSubnet3: !GetAtt EKSVPCStack.Outputs.PrivateSubnet3

      TemplateURL: https://s3.amazonaws.com/eksdevsecopsdemo/managed-nodegroup.yml

  EKSServiceStack:
    DependsOn: EKSMNGStack
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ResourceName: !Ref EnvironmentName

      TemplateURL: https://s3.amazonaws.com/eksdevsecopsdemo/eksservice.yml

  InitialPipeline:
    DependsOn: EKSServiceStack
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DevSecOpsResources: !Ref DevSecOpsResourcesBucket
        ResourceName: !Ref EnvironmentName
        FailWhen: !Ref FailWhen

      TemplateURL: https://s3.amazonaws.com/eksdevsecopsdemo/ekspipeline-setup.yml


Outputs: {}
